### ISSUE TITLE
Create barcode puts wrong SSID when SSID!=Network name

### ISSUE THREAD

**Issue by azrdev** [muelli/network-manager-qrcode#1]
In Networkmanager, edit one of your wifi networks. Alter the network name, so it doesn't match the SSID anymore.
Use `create_barcode_from_wifi.py` to share that connection.
* Expected: The shared barcode contains the original SSID
* Actual: It contains the network name, which fails to connect

**Comment by muelli** [comment]
fixed https://github.com/muelli/network-manager-qrcode/commit/987a69e46c97ad6b85fdafdb230b0074dbe397cb
